# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\python\Serial_debugger\Serial_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1222, 873)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(790, 490))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Mainico/主.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setIconSize(QtCore.QSize(32, 32))
        self.tabWidget.setObjectName("tabWidget")
        self.Main = QtWidgets.QWidget()
        self.Main.setObjectName("Main")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Main)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(380, 0))
        self.frame.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 354, 687))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.openSerialButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openSerialButton.sizePolicy().hasHeightForWidth())
        self.openSerialButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.openSerialButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/MainWin/ico/20200510-223354.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openSerialButton.setIcon(icon1)
        self.openSerialButton.setIconSize(QtCore.QSize(32, 32))
        self.openSerialButton.setObjectName("openSerialButton")
        self.gridLayout_5.addWidget(self.openSerialButton, 1, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_5.addWidget(self.line_2, 5, 0, 1, 2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.customCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customCheckBox.sizePolicy().hasHeightForWidth())
        self.customCheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.customCheckBox.setFont(font)
        self.customCheckBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.customCheckBox.setObjectName("customCheckBox")
        self.gridLayout_4.addWidget(self.customCheckBox, 3, 2, 1, 2)
        self.autoConnectLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoConnectLineEdit.sizePolicy().hasHeightForWidth())
        self.autoConnectLineEdit.setSizePolicy(sizePolicy)
        self.autoConnectLineEdit.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.autoConnectLineEdit.setFont(font)
        self.autoConnectLineEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.autoConnectLineEdit.setObjectName("autoConnectLineEdit")
        self.gridLayout_4.addWidget(self.autoConnectLineEdit, 1, 2, 1, 2)
        self.autoConnectCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoConnectCheckBox.sizePolicy().hasHeightForWidth())
        self.autoConnectCheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.autoConnectCheckBox.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/MainWin/ico/20200510-230228.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.autoConnectCheckBox.setIcon(icon2)
        self.autoConnectCheckBox.setIconSize(QtCore.QSize(25, 25))
        self.autoConnectCheckBox.setObjectName("autoConnectCheckBox")
        self.gridLayout_4.addWidget(self.autoConnectCheckBox, 1, 0, 1, 2)
        self.fastConnectRadioButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fastConnectRadioButton.sizePolicy().hasHeightForWidth())
        self.fastConnectRadioButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.fastConnectRadioButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/MainWin/ico/20200510-230220.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fastConnectRadioButton.setIcon(icon3)
        self.fastConnectRadioButton.setIconSize(QtCore.QSize(25, 25))
        self.fastConnectRadioButton.setAutoExclusive(False)
        self.fastConnectRadioButton.setObjectName("fastConnectRadioButton")
        self.gridLayout_4.addWidget(self.fastConnectRadioButton, 3, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_4, 8, 0, 1, 2)
        self.connectStateRadioButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectStateRadioButton.sizePolicy().hasHeightForWidth())
        self.connectStateRadioButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.connectStateRadioButton.setFont(font)
        self.connectStateRadioButton.setText("")
        self.connectStateRadioButton.setCheckable(False)
        self.connectStateRadioButton.setChecked(False)
        self.connectStateRadioButton.setAutoExclusive(False)
        self.connectStateRadioButton.setObjectName("connectStateRadioButton")
        self.gridLayout_5.addWidget(self.connectStateRadioButton, 1, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_5.addWidget(self.line_3, 7, 0, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cutFrameCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cutFrameCheckBox.sizePolicy().hasHeightForWidth())
        self.cutFrameCheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.cutFrameCheckBox.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/MainWin/ico/20200510-223345.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cutFrameCheckBox.setIcon(icon4)
        self.cutFrameCheckBox.setChecked(True)
        self.cutFrameCheckBox.setObjectName("cutFrameCheckBox")
        self.gridLayout_2.addWidget(self.cutFrameCheckBox, 1, 0, 1, 1)
        self.saveMsgPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveMsgPushButton.sizePolicy().hasHeightForWidth())
        self.saveMsgPushButton.setSizePolicy(sizePolicy)
        self.saveMsgPushButton.setMinimumSize(QtCore.QSize(158, 0))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.saveMsgPushButton.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Mainico/ico/20200510-221417.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveMsgPushButton.setIcon(icon5)
        self.saveMsgPushButton.setIconSize(QtCore.QSize(22, 22))
        self.saveMsgPushButton.setObjectName("saveMsgPushButton")
        self.gridLayout_2.addWidget(self.saveMsgPushButton, 2, 0, 1, 1)
        self.cutTimeSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cutTimeSpinBox.sizePolicy().hasHeightForWidth())
        self.cutTimeSpinBox.setSizePolicy(sizePolicy)
        self.cutTimeSpinBox.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.cutTimeSpinBox.setFont(font)
        self.cutTimeSpinBox.setMaximum(2000)
        self.cutTimeSpinBox.setObjectName("cutTimeSpinBox")
        self.gridLayout_2.addWidget(self.cutTimeSpinBox, 1, 1, 1, 1)
        self.cleanMsgPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cleanMsgPushButton.sizePolicy().hasHeightForWidth())
        self.cleanMsgPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.cleanMsgPushButton.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/MainWin/ico/20200510-223403.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cleanMsgPushButton.setIcon(icon6)
        self.cleanMsgPushButton.setIconSize(QtCore.QSize(25, 25))
        self.cleanMsgPushButton.setObjectName("cleanMsgPushButton")
        self.gridLayout_2.addWidget(self.cleanMsgPushButton, 2, 1, 1, 2)
        self.showSendCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showSendCheckBox.sizePolicy().hasHeightForWidth())
        self.showSendCheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.showSendCheckBox.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/MainWin/ico/20200510-235146.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showSendCheckBox.setIcon(icon7)
        self.showSendCheckBox.setIconSize(QtCore.QSize(25, 25))
        self.showSendCheckBox.setObjectName("showSendCheckBox")
        self.gridLayout_2.addWidget(self.showSendCheckBox, 0, 1, 1, 2)
        self.cutLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cutLabel.sizePolicy().hasHeightForWidth())
        self.cutLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.cutLabel.setFont(font)
        self.cutLabel.setObjectName("cutLabel")
        self.gridLayout_2.addWidget(self.cutLabel, 1, 2, 1, 1)
        self.showHexCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showHexCheckBox.sizePolicy().hasHeightForWidth())
        self.showHexCheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.showHexCheckBox.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Mainico/ico/20200510-234010.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showHexCheckBox.setIcon(icon8)
        self.showHexCheckBox.setIconSize(QtCore.QSize(25, 25))
        self.showHexCheckBox.setObjectName("showHexCheckBox")
        self.gridLayout_2.addWidget(self.showHexCheckBox, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 4, 0, 1, 2)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.byteSizeLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.byteSizeLabel.sizePolicy().hasHeightForWidth())
        self.byteSizeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.byteSizeLabel.setFont(font)
        self.byteSizeLabel.setObjectName("byteSizeLabel")
        self.gridLayout.addWidget(self.byteSizeLabel, 3, 0, 1, 1)
        self.stopBitsComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopBitsComboBox.sizePolicy().hasHeightForWidth())
        self.stopBitsComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.stopBitsComboBox.setFont(font)
        self.stopBitsComboBox.setObjectName("stopBitsComboBox")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/MainWin/ico/20200510-223417.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopBitsComboBox.addItem(icon9, "")
        self.stopBitsComboBox.addItem(icon9, "")
        self.stopBitsComboBox.addItem(icon9, "")
        self.gridLayout.addWidget(self.stopBitsComboBox, 5, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.byteSizeComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.byteSizeComboBox.sizePolicy().hasHeightForWidth())
        self.byteSizeComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.byteSizeComboBox.setFont(font)
        self.byteSizeComboBox.setObjectName("byteSizeComboBox")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/MainWin/ico/20200510-223408.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.byteSizeComboBox.addItem(icon10, "")
        self.byteSizeComboBox.addItem(icon10, "")
        self.byteSizeComboBox.addItem(icon10, "")
        self.byteSizeComboBox.addItem(icon10, "")
        self.gridLayout.addWidget(self.byteSizeComboBox, 3, 2, 1, 1)
        self.stopBitsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopBitsLabel.sizePolicy().hasHeightForWidth())
        self.stopBitsLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.stopBitsLabel.setFont(font)
        self.stopBitsLabel.setObjectName("stopBitsLabel")
        self.gridLayout.addWidget(self.stopBitsLabel, 5, 0, 1, 1)
        self.parityComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parityComboBox.sizePolicy().hasHeightForWidth())
        self.parityComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.parityComboBox.setFont(font)
        self.parityComboBox.setObjectName("parityComboBox")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/MainWin/ico/20200510-223427.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.parityComboBox.addItem(icon11, "")
        self.parityComboBox.addItem(icon11, "")
        self.parityComboBox.addItem(icon11, "")
        self.parityComboBox.addItem(icon11, "")
        self.gridLayout.addWidget(self.parityComboBox, 4, 2, 1, 1)
        self.bpsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bpsLabel.sizePolicy().hasHeightForWidth())
        self.bpsLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.bpsLabel.setFont(font)
        self.bpsLabel.setObjectName("bpsLabel")
        self.gridLayout.addWidget(self.bpsLabel, 2, 0, 1, 1)
        self.bpscomboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bpscomboBox.sizePolicy().hasHeightForWidth())
        self.bpscomboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.bpscomboBox.setFont(font)
        self.bpscomboBox.setObjectName("bpscomboBox")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/MainWin/ico/20200510-223358.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bpscomboBox.addItem(icon12, "")
        self.bpscomboBox.addItem(icon12, "")
        self.bpscomboBox.addItem(icon12, "")
        self.bpscomboBox.addItem(icon12, "")
        self.bpscomboBox.addItem(icon12, "")
        self.bpscomboBox.addItem(icon12, "")
        self.bpscomboBox.addItem(icon12, "")
        self.bpscomboBox.addItem(icon12, "")
        self.bpscomboBox.addItem(icon12, "")
        self.bpscomboBox.addItem(icon12, "")
        self.bpscomboBox.addItem(icon12, "")
        self.gridLayout.addWidget(self.bpscomboBox, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 1, 1, 1)
        self.parityLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parityLabel.sizePolicy().hasHeightForWidth())
        self.parityLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.parityLabel.setFont(font)
        self.parityLabel.setObjectName("parityLabel")
        self.gridLayout.addWidget(self.parityLabel, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_7, 0, 0, 1, 2)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.line_7.setFont(font)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_5.addWidget(self.line_7, 11, 0, 1, 2)
        self.searchSerialButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchSerialButton.sizePolicy().hasHeightForWidth())
        self.searchSerialButton.setSizePolicy(sizePolicy)
        self.searchSerialButton.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.searchSerialButton.setFont(font)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/MainWin/ico/20200510-223413.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchSerialButton.setIcon(icon13)
        self.searchSerialButton.setIconSize(QtCore.QSize(23, 23))
        self.searchSerialButton.setObjectName("searchSerialButton")
        self.gridLayout_5.addWidget(self.searchSerialButton, 13, 0, 1, 2)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 2, 0, 1, 2)
        self.serialListWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serialListWidget.sizePolicy().hasHeightForWidth())
        self.serialListWidget.setSizePolicy(sizePolicy)
        self.serialListWidget.setMinimumSize(QtCore.QSize(0, 50))
        self.serialListWidget.setMaximumSize(QtCore.QSize(16777215, 98))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.serialListWidget.setFont(font)
        self.serialListWidget.setObjectName("serialListWidget")
        self.gridLayout_5.addWidget(self.serialListWidget, 14, 0, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 12, 0, 1, 2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_3.addWidget(self.checkBox_2, 2, 2, 1, 1)
        self.sendHexCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendHexCheckBox.sizePolicy().hasHeightForWidth())
        self.sendHexCheckBox.setSizePolicy(sizePolicy)
        self.sendHexCheckBox.setMinimumSize(QtCore.QSize(158, 0))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.sendHexCheckBox.setFont(font)
        self.sendHexCheckBox.setIcon(icon8)
        self.sendHexCheckBox.setIconSize(QtCore.QSize(25, 25))
        self.sendHexCheckBox.setObjectName("sendHexCheckBox")
        self.gridLayout_3.addWidget(self.sendHexCheckBox, 0, 0, 1, 2)
        self.sendTimeCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendTimeCheckBox.sizePolicy().hasHeightForWidth())
        self.sendTimeCheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.sendTimeCheckBox.setFont(font)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/MainWin/ico/20200510-230202.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendTimeCheckBox.setIcon(icon14)
        self.sendTimeCheckBox.setIconSize(QtCore.QSize(25, 25))
        self.sendTimeCheckBox.setObjectName("sendTimeCheckBox")
        self.gridLayout_3.addWidget(self.sendTimeCheckBox, 1, 0, 1, 2)
        self.checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 2, 3, 1, 6)
        self.sendTimeSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendTimeSpinBox.sizePolicy().hasHeightForWidth())
        self.sendTimeSpinBox.setSizePolicy(sizePolicy)
        self.sendTimeSpinBox.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.sendTimeSpinBox.setFont(font)
        self.sendTimeSpinBox.setMinimum(1)
        self.sendTimeSpinBox.setMaximum(20000)
        self.sendTimeSpinBox.setObjectName("sendTimeSpinBox")
        self.gridLayout_3.addWidget(self.sendTimeSpinBox, 1, 2, 1, 2)
        self.lineChangeComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineChangeComboBox.sizePolicy().hasHeightForWidth())
        self.lineChangeComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.lineChangeComboBox.setFont(font)
        self.lineChangeComboBox.setObjectName("lineChangeComboBox")
        self.lineChangeComboBox.addItem("")
        self.lineChangeComboBox.addItem("")
        self.lineChangeComboBox.addItem("")
        self.lineChangeComboBox.addItem("")
        self.gridLayout_3.addWidget(self.lineChangeComboBox, 2, 1, 1, 1)
        self.lineChangeLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineChangeLabel.sizePolicy().hasHeightForWidth())
        self.lineChangeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.lineChangeLabel.setFont(font)
        self.lineChangeLabel.setObjectName("lineChangeLabel")
        self.gridLayout_3.addWidget(self.lineChangeLabel, 2, 0, 1, 1)
        self.enterSendCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enterSendCheckBox.sizePolicy().hasHeightForWidth())
        self.enterSendCheckBox.setSizePolicy(sizePolicy)
        self.enterSendCheckBox.setMinimumSize(QtCore.QSize(158, 0))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.enterSendCheckBox.setFont(font)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Mainico/ico/20200510-234445.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.enterSendCheckBox.setIcon(icon15)
        self.enterSendCheckBox.setIconSize(QtCore.QSize(23, 23))
        self.enterSendCheckBox.setObjectName("enterSendCheckBox")
        self.gridLayout_3.addWidget(self.enterSendCheckBox, 0, 2, 1, 7)
        self.sendTimeLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendTimeLabel.sizePolicy().hasHeightForWidth())
        self.sendTimeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.sendTimeLabel.setFont(font)
        self.sendTimeLabel.setObjectName("sendTimeLabel")
        self.gridLayout_3.addWidget(self.sendTimeLabel, 1, 4, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 6, 0, 1, 2)
        self.horizontalLayout_4.addLayout(self.gridLayout_5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.showLabel1 = QtWidgets.QLabel(self.frame)
        self.showLabel1.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.showLabel1.setFont(font)
        self.showLabel1.setObjectName("showLabel1")
        self.horizontalLayout_5.addWidget(self.showLabel1)
        self.sendCountLabel = QtWidgets.QLabel(self.frame)
        self.sendCountLabel.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.sendCountLabel.setFont(font)
        self.sendCountLabel.setObjectName("sendCountLabel")
        self.horizontalLayout_5.addWidget(self.sendCountLabel)
        self.showLabel2 = QtWidgets.QLabel(self.frame)
        self.showLabel2.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.showLabel2.setFont(font)
        self.showLabel2.setObjectName("showLabel2")
        self.horizontalLayout_5.addWidget(self.showLabel2)
        self.receiveCountLabel = QtWidgets.QLabel(self.frame)
        self.receiveCountLabel.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.receiveCountLabel.setFont(font)
        self.receiveCountLabel.setObjectName("receiveCountLabel")
        self.horizontalLayout_5.addWidget(self.receiveCountLabel)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 1, 0, 1, 2)
        self.versionLabel = QtWidgets.QLabel(self.frame)
        self.versionLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.versionLabel.setFont(font)
        self.versionLabel.setWordWrap(False)
        self.versionLabel.setOpenExternalLinks(True)
        self.versionLabel.setObjectName("versionLabel")
        self.gridLayout_6.addWidget(self.versionLabel, 2, 0, 1, 1)
        self.cleanMessageButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cleanMessageButton.sizePolicy().hasHeightForWidth())
        self.cleanMessageButton.setSizePolicy(sizePolicy)
        self.cleanMessageButton.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.cleanMessageButton.setFont(font)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/Mainico/ico/20200510-221413.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cleanMessageButton.setIcon(icon16)
        self.cleanMessageButton.setIconSize(QtCore.QSize(20, 20))
        self.cleanMessageButton.setObjectName("cleanMessageButton")
        self.gridLayout_6.addWidget(self.cleanMessageButton, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_6)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.messageBox = QtWidgets.QLabel(self.Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageBox.sizePolicy().hasHeightForWidth())
        self.messageBox.setSizePolicy(sizePolicy)
        self.messageBox.setMinimumSize(QtCore.QSize(0, 0))
        self.messageBox.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.messageBox.setFont(font)
        self.messageBox.setText("")
        self.messageBox.setObjectName("messageBox")
        self.verticalLayout.addWidget(self.messageBox)
        self.receiveBox = QtWidgets.QPlainTextEdit(self.Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.receiveBox.sizePolicy().hasHeightForWidth())
        self.receiveBox.setSizePolicy(sizePolicy)
        self.receiveBox.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.receiveBox.setFont(font)
        self.receiveBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.receiveBox.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.receiveBox.setDocumentTitle("")
        self.receiveBox.setReadOnly(True)
        self.receiveBox.setPlainText("")
        self.receiveBox.setBackgroundVisible(False)
        self.receiveBox.setCenterOnScroll(False)
        self.receiveBox.setObjectName("receiveBox")
        self.verticalLayout.addWidget(self.receiveBox)
        self.toolBox = QtWidgets.QToolBox(self.Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.toolBox.setFont(font)
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.toolBox.setLineWidth(1)
        self.toolBox.setMidLineWidth(0)
        self.toolBox.setObjectName("toolBox")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 783, 172))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sendLayout = QtWidgets.QHBoxLayout()
        self.sendLayout.setSpacing(5)
        self.sendLayout.setObjectName("sendLayout")
        self.sendBox = QtWidgets.QPlainTextEdit(self.page_3)
        self.sendBox.setMinimumSize(QtCore.QSize(100, 0))
        self.sendBox.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.sendBox.setFont(font)
        self.sendBox.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.sendBox.setPlainText("")
        self.sendBox.setObjectName("sendBox")
        self.sendLayout.addWidget(self.sendBox)
        self.sendButton = QtWidgets.QPushButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton.sizePolicy().hasHeightForWidth())
        self.sendButton.setSizePolicy(sizePolicy)
        self.sendButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.sendButton.setFont(font)
        self.sendButton.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/Mainico/ico/20200510-221424.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendButton.setIcon(icon17)
        self.sendButton.setIconSize(QtCore.QSize(50, 50))
        self.sendButton.setObjectName("sendButton")
        self.sendLayout.addWidget(self.sendButton)
        self.verticalLayout_6.addLayout(self.sendLayout)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/MainWin/ico/20200510-230224.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_3, icon18, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 783, 172))
        self.page_4.setObjectName("page_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_4)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 738, 258))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.sendLine1_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.sendLine1_2.setObjectName("sendLine1_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sendLine1_2)
        self.sendLine1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.sendLine1.setObjectName("sendLine1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sendLine1)
        self.sendButton1_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.sendButton1_2.setIcon(icon18)
        self.sendButton1_2.setObjectName("sendButton1_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sendButton1_2)
        self.sendButton1_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton1_3.sizePolicy().hasHeightForWidth())
        self.sendButton1_3.setSizePolicy(sizePolicy)
        self.sendButton1_3.setIcon(icon18)
        self.sendButton1_3.setObjectName("sendButton1_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sendButton1_3)
        self.sendButton1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.sendButton1.setIcon(icon18)
        self.sendButton1.setObjectName("sendButton1")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.sendButton1)
        self.sendLine1_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendLine1_3.sizePolicy().hasHeightForWidth())
        self.sendLine1_3.setSizePolicy(sizePolicy)
        self.sendLine1_3.setObjectName("sendLine1_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sendLine1_3)
        self.sendLine1_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.sendLine1_4.setObjectName("sendLine1_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sendLine1_4)
        self.sendButton1_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.sendButton1_4.setIcon(icon18)
        self.sendButton1_4.setObjectName("sendButton1_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.sendButton1_4)
        self.sendLine1_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.sendLine1_5.setObjectName("sendLine1_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sendLine1_5)
        self.sendButton1_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.sendButton1_5.setIcon(icon18)
        self.sendButton1_5.setObjectName("sendButton1_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.sendButton1_5)
        self.sendLine1_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.sendLine1_6.setObjectName("sendLine1_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.sendLine1_6)
        self.sendButton1_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.sendButton1_6.setIcon(icon18)
        self.sendButton1_6.setObjectName("sendButton1_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.sendButton1_6)
        self.verticalLayout_8.addLayout(self.formLayout)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.addWidget(self.scrollArea_2)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/MainWin/ico/20200510-230208.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_4, icon19, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/Mainico/ico/20200510-214549.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.Main, icon20, "")
        self.Draw = QtWidgets.QWidget()
        self.Draw.setObjectName("Draw")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Draw)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.graphWidget = QtWidgets.QWidget(self.Draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphWidget.sizePolicy().hasHeightForWidth())
        self.graphWidget.setSizePolicy(sizePolicy)
        self.graphWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.graphWidget.setObjectName("graphWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.graphWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.graph_Layout = QtWidgets.QVBoxLayout()
        self.graph_Layout.setObjectName("graph_Layout")
        self.verticalLayout_5.addLayout(self.graph_Layout)
        self.verticalLayout_4.addWidget(self.graphWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.graphMsgBox = QtWidgets.QLabel(self.Draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphMsgBox.sizePolicy().hasHeightForWidth())
        self.graphMsgBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.graphMsgBox.setFont(font)
        self.graphMsgBox.setText("")
        self.graphMsgBox.setObjectName("graphMsgBox")
        self.horizontalLayout_6.addWidget(self.graphMsgBox)
        self.cleanGraphMsgButton = QtWidgets.QPushButton(self.Draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cleanGraphMsgButton.sizePolicy().hasHeightForWidth())
        self.cleanGraphMsgButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.cleanGraphMsgButton.setFont(font)
        self.cleanGraphMsgButton.setIcon(icon16)
        self.cleanGraphMsgButton.setObjectName("cleanGraphMsgButton")
        self.horizontalLayout_6.addWidget(self.cleanGraphMsgButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.graphReceiveBox = QtWidgets.QPlainTextEdit(self.Draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphReceiveBox.sizePolicy().hasHeightForWidth())
        self.graphReceiveBox.setSizePolicy(sizePolicy)
        self.graphReceiveBox.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.graphReceiveBox.setFont(font)
        self.graphReceiveBox.setObjectName("graphReceiveBox")
        self.horizontalLayout_3.addWidget(self.graphReceiveBox)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphSendBox = QtWidgets.QPlainTextEdit(self.Draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphSendBox.sizePolicy().hasHeightForWidth())
        self.graphSendBox.setSizePolicy(sizePolicy)
        self.graphSendBox.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.graphSendBox.setFont(font)
        self.graphSendBox.setObjectName("graphSendBox")
        self.verticalLayout_2.addWidget(self.graphSendBox)
        self.graphSendButton = QtWidgets.QPushButton(self.Draw)
        self.graphSendButton.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.graphSendButton.setFont(font)
        self.graphSendButton.setText("")
        self.graphSendButton.setIcon(icon17)
        self.graphSendButton.setIconSize(QtCore.QSize(40, 40))
        self.graphSendButton.setObjectName("graphSendButton")
        self.verticalLayout_2.addWidget(self.graphSendButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_3 = QtWidgets.QLabel(self.Draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 4, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 4, 0, 1, 1)
        self.addGraphColor = QtWidgets.QPushButton(self.Draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addGraphColor.sizePolicy().hasHeightForWidth())
        self.addGraphColor.setSizePolicy(sizePolicy)
        self.addGraphColor.setMinimumSize(QtCore.QSize(150, 0))
        self.addGraphColor.setMaximumSize(QtCore.QSize(170, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.addGraphColor.setFont(font)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/MainWin/ico/20200510-223440.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addGraphColor.setIcon(icon21)
        self.addGraphColor.setIconSize(QtCore.QSize(28, 28))
        self.addGraphColor.setObjectName("addGraphColor")
        self.gridLayout_8.addWidget(self.addGraphColor, 5, 0, 1, 3)
        self.clearDataButton = QtWidgets.QPushButton(self.Draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearDataButton.sizePolicy().hasHeightForWidth())
        self.clearDataButton.setSizePolicy(sizePolicy)
        self.clearDataButton.setMinimumSize(QtCore.QSize(150, 0))
        self.clearDataButton.setMaximumSize(QtCore.QSize(170, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.clearDataButton.setFont(font)
        self.clearDataButton.setIcon(icon6)
        self.clearDataButton.setIconSize(QtCore.QSize(28, 28))
        self.clearDataButton.setObjectName("clearDataButton")
        self.gridLayout_8.addWidget(self.clearDataButton, 5, 3, 1, 3)
        self.graphColorComboBox = QtWidgets.QComboBox(self.Draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphColorComboBox.sizePolicy().hasHeightForWidth())
        self.graphColorComboBox.setSizePolicy(sizePolicy)
        self.graphColorComboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.graphColorComboBox.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.graphColorComboBox.setFont(font)
        self.graphColorComboBox.setIconSize(QtCore.QSize(20, 20))
        self.graphColorComboBox.setDuplicatesEnabled(False)
        self.graphColorComboBox.setObjectName("graphColorComboBox")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/color/ico/20200510-221407.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.graphColorComboBox.addItem(icon22, "")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/color/ico/20200510-221359.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.graphColorComboBox.addItem(icon23, "")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/color/ico/20200510-221403.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.graphColorComboBox.addItem(icon24, "")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/color/ico/20200510-221356.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.graphColorComboBox.addItem(icon25, "")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/color/ico/20200510-221348.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.graphColorComboBox.addItem(icon26, "")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/color/ico/20200510-221351.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.graphColorComboBox.addItem(icon27, "")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/color/ico/20200510-221322.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.graphColorComboBox.addItem(icon28, "")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/color/ico/20200510-221319.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.graphColorComboBox.addItem(icon29, "")
        self.gridLayout_8.addWidget(self.graphColorComboBox, 4, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.Draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 3, 0, 1, 1)
        self.backColorComboBox = QtWidgets.QComboBox(self.Draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backColorComboBox.sizePolicy().hasHeightForWidth())
        self.backColorComboBox.setSizePolicy(sizePolicy)
        self.backColorComboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.backColorComboBox.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.backColorComboBox.setFont(font)
        self.backColorComboBox.setToolTip("")
        self.backColorComboBox.setObjectName("backColorComboBox")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/color/ico/20200510-221335.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.backColorComboBox.addItem(icon30, "")
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/color/ico/20200510-221322.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.backColorComboBox.addItem(icon31, "")
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/color/ico/20200510-221333.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.backColorComboBox.addItem(icon32, "")
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/color/ico/20200510-221329.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.backColorComboBox.addItem(icon33, "")
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/color/ico/20200510-221319.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.backColorComboBox.addItem(icon34, "")
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/color/ico/20200510-221325.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.backColorComboBox.addItem(icon35, "")
        self.gridLayout_8.addWidget(self.backColorComboBox, 3, 1, 1, 2)
        self.limitLenSpinBox = QtWidgets.QSpinBox(self.Draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.limitLenSpinBox.sizePolicy().hasHeightForWidth())
        self.limitLenSpinBox.setSizePolicy(sizePolicy)
        self.limitLenSpinBox.setMinimumSize(QtCore.QSize(80, 0))
        self.limitLenSpinBox.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.limitLenSpinBox.setFont(font)
        self.limitLenSpinBox.setMinimum(10)
        self.limitLenSpinBox.setMaximum(10000)
        self.limitLenSpinBox.setObjectName("limitLenSpinBox")
        self.gridLayout_8.addWidget(self.limitLenSpinBox, 3, 5, 1, 1)
        self.graphColorName = QtWidgets.QLineEdit(self.Draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphColorName.sizePolicy().hasHeightForWidth())
        self.graphColorName.setSizePolicy(sizePolicy)
        self.graphColorName.setMinimumSize(QtCore.QSize(0, 30))
        self.graphColorName.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.graphColorName.setFont(font)
        self.graphColorName.setObjectName("graphColorName")
        self.gridLayout_8.addWidget(self.graphColorName, 4, 4, 1, 2)
        self.limitCheckBox = QtWidgets.QCheckBox(self.Draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.limitCheckBox.sizePolicy().hasHeightForWidth())
        self.limitCheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.limitCheckBox.setFont(font)
        self.limitCheckBox.setObjectName("limitCheckBox")
        self.gridLayout_8.addWidget(self.limitCheckBox, 3, 3, 1, 2)
        self.saveDataButton = QtWidgets.QPushButton(self.Draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveDataButton.sizePolicy().hasHeightForWidth())
        self.saveDataButton.setSizePolicy(sizePolicy)
        self.saveDataButton.setMinimumSize(QtCore.QSize(150, 0))
        self.saveDataButton.setMaximumSize(QtCore.QSize(170, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.saveDataButton.setFont(font)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/MainWin/ico/20200510-223336.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveDataButton.setIcon(icon36)
        self.saveDataButton.setIconSize(QtCore.QSize(28, 28))
        self.saveDataButton.setObjectName("saveDataButton")
        self.gridLayout_8.addWidget(self.saveDataButton, 6, 3, 1, 3)
        self.moreConfigButton = QtWidgets.QPushButton(self.Draw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moreConfigButton.sizePolicy().hasHeightForWidth())
        self.moreConfigButton.setSizePolicy(sizePolicy)
        self.moreConfigButton.setMinimumSize(QtCore.QSize(150, 0))
        self.moreConfigButton.setMaximumSize(QtCore.QSize(170, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(13)
        self.moreConfigButton.setFont(font)
        self.moreConfigButton.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/Mainico/ico/20200510-215416.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moreConfigButton.setIcon(icon37)
        self.moreConfigButton.setIconSize(QtCore.QSize(28, 28))
        self.moreConfigButton.setObjectName("moreConfigButton")
        self.gridLayout_8.addWidget(self.moreConfigButton, 6, 0, 1, 3)
        self.horizontalLayout_3.addLayout(self.gridLayout_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(":/Mainico/ico/20200510-214540.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.Draw, icon38, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(":/Mainico/ico/20200510-215416.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_2, icon39, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_12.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_12.addWidget(self.label, 1, 0, 1, 1)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(":/Mainico/ico/20200510-214533.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab, icon40, "")
        self.gridLayout_10.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.byteSizeLabel.setBuddy(self.byteSizeComboBox)
        self.stopBitsLabel.setBuddy(self.stopBitsComboBox)
        self.bpsLabel.setBuddy(self.bpscomboBox)
        self.parityLabel.setBuddy(self.parityComboBox)
        self.lineChangeLabel.setBuddy(self.lineChangeComboBox)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "小智串口调试器"))
        self.openSerialButton.setToolTip(_translate("MainWindow", "默认连接CH340"))
        self.openSerialButton.setText(_translate("MainWindow", "打开串口"))
        self.customCheckBox.setToolTip(_translate("MainWindow", "自定义数据包"))
        self.customCheckBox.setText(_translate("MainWindow", "自定义数据包"))
        self.autoConnectLineEdit.setToolTip(_translate("MainWindow", "设备关键字"))
        self.autoConnectLineEdit.setText(_translate("MainWindow", "CH340"))
        self.autoConnectCheckBox.setText(_translate("MainWindow", "自动连接"))
        self.fastConnectRadioButton.setToolTip(_translate("MainWindow", "在启动时优先访问某一串口"))
        self.fastConnectRadioButton.setText(_translate("MainWindow", "快速连接"))
        self.cutFrameCheckBox.setText(_translate("MainWindow", "自动断帧"))
        self.saveMsgPushButton.setText(_translate("MainWindow", "保存数据"))
        self.cleanMsgPushButton.setText(_translate("MainWindow", "清空接收"))
        self.showSendCheckBox.setText(_translate("MainWindow", "暂停显示"))
        self.cutLabel.setText(_translate("MainWindow", "ms"))
        self.showHexCheckBox.setText(_translate("MainWindow", "显示HEX"))
        self.byteSizeLabel.setText(_translate("MainWindow", "数据位:"))
        self.stopBitsComboBox.setItemText(0, _translate("MainWindow", "1"))
        self.stopBitsComboBox.setItemText(1, _translate("MainWindow", "1.5"))
        self.stopBitsComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.byteSizeComboBox.setCurrentText(_translate("MainWindow", "5"))
        self.byteSizeComboBox.setItemText(0, _translate("MainWindow", "5"))
        self.byteSizeComboBox.setItemText(1, _translate("MainWindow", "6"))
        self.byteSizeComboBox.setItemText(2, _translate("MainWindow", "7"))
        self.byteSizeComboBox.setItemText(3, _translate("MainWindow", "8"))
        self.stopBitsLabel.setText(_translate("MainWindow", "停止位:"))
        self.parityComboBox.setItemText(0, _translate("MainWindow", "None"))
        self.parityComboBox.setItemText(1, _translate("MainWindow", "Even"))
        self.parityComboBox.setItemText(2, _translate("MainWindow", "Mark"))
        self.parityComboBox.setItemText(3, _translate("MainWindow", "Odd"))
        self.bpsLabel.setText(_translate("MainWindow", "波特率:"))
        self.bpscomboBox.setCurrentText(_translate("MainWindow", "1800"))
        self.bpscomboBox.setItemText(0, _translate("MainWindow", "1800"))
        self.bpscomboBox.setItemText(1, _translate("MainWindow", "2400"))
        self.bpscomboBox.setItemText(2, _translate("MainWindow", "4800"))
        self.bpscomboBox.setItemText(3, _translate("MainWindow", "9600"))
        self.bpscomboBox.setItemText(4, _translate("MainWindow", "19200"))
        self.bpscomboBox.setItemText(5, _translate("MainWindow", "38400"))
        self.bpscomboBox.setItemText(6, _translate("MainWindow", "57600"))
        self.bpscomboBox.setItemText(7, _translate("MainWindow", "115200"))
        self.bpscomboBox.setItemText(8, _translate("MainWindow", "230400"))
        self.bpscomboBox.setItemText(9, _translate("MainWindow", "460800"))
        self.bpscomboBox.setItemText(10, _translate("MainWindow", "921600"))
        self.parityLabel.setText(_translate("MainWindow", "校验位:"))
        self.searchSerialButton.setText(_translate("MainWindow", "搜索串口"))
        self.checkBox_2.setText(_translate("MainWindow", "DTR   "))
        self.sendHexCheckBox.setToolTip(_translate("MainWindow", "使用空格分隔"))
        self.sendHexCheckBox.setText(_translate("MainWindow", "发送HEX"))
        self.sendTimeCheckBox.setText(_translate("MainWindow", "定时发送"))
        self.checkBox.setText(_translate("MainWindow", "RTS"))
        self.lineChangeComboBox.setItemText(0, _translate("MainWindow", "\\r\\n"))
        self.lineChangeComboBox.setItemText(1, _translate("MainWindow", "\\r"))
        self.lineChangeComboBox.setItemText(2, _translate("MainWindow", "\\n"))
        self.lineChangeComboBox.setItemText(3, _translate("MainWindow", "None"))
        self.lineChangeLabel.setText(_translate("MainWindow", "换行符"))
        self.enterSendCheckBox.setToolTip(_translate("MainWindow", "使用空格分隔"))
        self.enterSendCheckBox.setText(_translate("MainWindow", "回车发送"))
        self.sendTimeLabel.setText(_translate("MainWindow", "ms"))
        self.showLabel1.setText(_translate("MainWindow", "发送"))
        self.sendCountLabel.setText(_translate("MainWindow", "--"))
        self.showLabel2.setText(_translate("MainWindow", "接收"))
        self.receiveCountLabel.setText(_translate("MainWindow", "--"))
        self.versionLabel.setToolTip(_translate("MainWindow", "测试版本"))
        self.versionLabel.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://github.com/Unarvest/Serial-Debug\"><span style=\" text-decoration: underline; color:#000000;\">Alpha 0.510.2</span></a></p></body></html>"))
        self.cleanMessageButton.setToolTip(_translate("MainWindow", "清空接收和发送计数"))
        self.cleanMessageButton.setText(_translate("MainWindow", "清空状态"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "单条发送"))
        self.sendButton1_2.setText(_translate("MainWindow", "发送1"))
        self.sendButton1_3.setText(_translate("MainWindow", "发送2"))
        self.sendButton1.setText(_translate("MainWindow", "发送3"))
        self.sendButton1_4.setText(_translate("MainWindow", "发送4"))
        self.sendButton1_5.setText(_translate("MainWindow", "发送5"))
        self.sendButton1_6.setText(_translate("MainWindow", "发送6"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "多条发送"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Main), _translate("MainWindow", "主页"))
        self.cleanGraphMsgButton.setText(_translate("MainWindow", "    清空消息    "))
        self.graphSendButton.setToolTip(_translate("MainWindow", "快捷发送，不支持十六进制"))
        self.label_3.setText(_translate("MainWindow", "标签"))
        self.label_2.setText(_translate("MainWindow", "颜色"))
        self.addGraphColor.setToolTip(_translate("MainWindow", "曲线与颜色对应"))
        self.addGraphColor.setText(_translate("MainWindow", "添加曲线"))
        self.clearDataButton.setToolTip(_translate("MainWindow", "清空所有！！"))
        self.clearDataButton.setText(_translate("MainWindow", "清空数据"))
        self.graphColorComboBox.setItemText(0, _translate("MainWindow", "红色"))
        self.graphColorComboBox.setItemText(1, _translate("MainWindow", "蓝色"))
        self.graphColorComboBox.setItemText(2, _translate("MainWindow", "绿色"))
        self.graphColorComboBox.setItemText(3, _translate("MainWindow", "青色"))
        self.graphColorComboBox.setItemText(4, _translate("MainWindow", "粉色"))
        self.graphColorComboBox.setItemText(5, _translate("MainWindow", "黄色"))
        self.graphColorComboBox.setItemText(6, _translate("MainWindow", "白色"))
        self.graphColorComboBox.setItemText(7, _translate("MainWindow", "黑色"))
        self.label_4.setText(_translate("MainWindow", "背景"))
        self.backColorComboBox.setItemText(0, _translate("MainWindow", "铅白"))
        self.backColorComboBox.setItemText(1, _translate("MainWindow", "纯白"))
        self.backColorComboBox.setItemText(2, _translate("MainWindow", "莹白"))
        self.backColorComboBox.setItemText(3, _translate("MainWindow", "素"))
        self.backColorComboBox.setItemText(4, _translate("MainWindow", "纯黑"))
        self.backColorComboBox.setItemText(5, _translate("MainWindow", "墨色"))
        self.graphColorName.setText(_translate("MainWindow", "Curve"))
        self.limitCheckBox.setToolTip(_translate("MainWindow", "限制横轴长度"))
        self.limitCheckBox.setText(_translate("MainWindow", "限制"))
        self.saveDataButton.setText(_translate("MainWindow", "导出图片"))
        self.moreConfigButton.setToolTip(_translate("MainWindow", "还没做，也不一定会做"))
        self.moreConfigButton.setText(_translate("MainWindow", "更多设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Draw), _translate("MainWindow", "绘图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "设置"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "-更新-\n"
"--------------------------\n"
"Alpha 0.54.1\n"
"-添加串口搜索功能\n"
"-添加串口选择功能\n"
"-添加状态提示\n"
"-添加换行符\n"
"-添加显示\n"
"-添加快速启动\n"
"-添加发送接收计数\n"
"-框架优化\n"
"-修了一堆bug\n"
"--------------------------\n"
"Alpha 0.54.2\n"
"-提示信息优化\n"
"-最大最小宽度优化\n"
"-修复bug:暂停显示和复选框显示错误\n"
"-修复bug:取消保存文件,但文件仍保存\n"
"--------------------------\n"
"Alpha 0.55.1\n"
"-优化窗体大小限制\n"
"-移除串口号选择, 数据包编辑框\n"
"-优化窗体布局\n"
"-为打开串口按钮添加状态指示\n"
"-优化串口状态标志位\n"
"--------------------------\n"
"Alpha 0.55.2\n"
"-优化串口号获取以兼容linux\n"
"-优化搜索串口提示信息\n"
"--------------------------\n"
"Alpha 0.55.3\n"
"-优化串口二次连接速度\n"
"-修复快速启动按钮显示错误\n"
"-修复串口信息编码报错导致的串口断开\n"
"--------------------------\n"
"Alpha 0.56.1\n"
"-添加定时发送功能\n"
"-添加回车发送\n"
"-优化快速连接,现已不会造成启动界面卡顿\n"
"-优化提示信息\n"
"--------------------------\n"
"Alpha 0.56.2\n"
"-修复回车发送空信息报错\n"
"--------------------------\n"
"Alpha 0.56.3\n"
"-修复回车发送后光标漂移\n"
"-发送现在可以回显出\\r\\n\n"
"-优化提示信息\n"
"--------------------------\n"
"Alpha 0.58.1\n"
"-修复信息接收窗不显示信息bug\n"
"-添加绘图功能\n"
"--------------------------\n"
"Alpha 0.58.2\n"
"-修复启动后无法正常连接bug\n"
"--------------------------\n"
"Alpha 0.58.3\n"
"-优化串口连接后的搜索串口功能\n"
"--------------------------\n"
"Alpha 0.59.1\n"
"-优化字体\n"
"-优化启动速度\n"
"-优化框架\n"
"-优化在不同系统缩放下的显示效果\n"
"--------------------------\n"
"Alpha 0.59.2\n"
"-修复信息接收显示上一条信息bug\n"
"--------------------------\n"
"Alpha 0.59.3\n"
"-修复快速启动时偶发的报错\n"
"-修复绘图添加曲线提示信息错误\n"
"-优化绘图功能效率\n"
"-添加绘图长度限制功能\n"
"-添加背景颜色选择功能\n"
"--------------------------\n"
"Alpha 0.59.4\n"
"-添加导出图片功能\n"
"-修复bug:信息接收后光标移至开头\n"
"--------------------------\n"
"Alpha 0.59.5\n"
"-修复绘图超出限制部分返回限制时丢失\n"
"--------------------------\n"
"Alpha 0.510.1\n"
"-优化框架\n"
"-添加主页配置栏滚动\n"
"-优化窗体大小限制\n"
"-添加绘图区信息提示\n"
"--------------------------\n"
"Alpha 0.510.2\n"
"-添加图标\n"
"-添加链接\n"
"-优化排版\n"
"-添加发送多条信息框\n"
"--------------------------\n"
"自定义数据包暂不可用\n"
"绘图功能待完善..."))
        self.label.setText(_translate("MainWindow", "发现bug请联系2286107961@qq.com"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "关于"))
import icoPack_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
